### ISSUE TITLE
[BUG/Request] Cant save files with SPACE in them.

### ISSUE THREAD

**Issue by Manniala** [AlpacaInTheNight/PromptsBrowser#16]
### Hey, first of all thx for the extension.

I have ran into a little problem, it wont save previews if they have spaces in them.

PromptsBrowser: 18:17:53 -> failed to save preview: file "F:/sd.webui/webui/outputs/txt2img-images/2023-10-02/realisticVisionV51_v51VAE/realisticVisionV51_v51VAE%20-%202023.%20Monday.%2002.%20October%20-%20kl.18.15.51.png" not found

Are there something you can do about it, or do i need to change the way i structure my images?
I like to have it like "realisticVisionV51_v51VAE - 2023. Monday. 02. October - kl.18.15.51"

**Comment by AlpacaInTheNight** [comment]
Hi. I think it was already fixed in the #11 and merged into main.

Can you update extension to the latest version and check again?
