### ISSUE TITLE
Dynamic Prompts Support

### ISSUE THREAD

**Issue by MatteCrystal** [AlpacaInTheNight/PromptsBrowser#27]
Dynamic prompts https://github.com/adieyal/sd-dynamic-prompts.git are almost supported out of the box already since you show { } and | symbols in the prompts view. 

However, I'm having 2 issues. 
# Trying to save this dynamic prompt 

```({ blue theme | red theme | orange theme | yellow theme | green theme | purple theme | pink theme | neon theme | gold theme}  { mixed with {blue theme | red theme | orange theme | yellow theme | green theme | purple theme | pink theme | neon theme | gold theme}  |  }  {and {blue background| red background| orange background| yellow background| green background| purple background| pink background| neon background | gold background}  |  }: 1.2)```

but when i load it it turns into the below example. The first portion of it seems to be cut off and most of the | symbols have be replaced with commas. Also the ( XYZ :1.2) strength that i wrapped it all in get's moved to the back and doesn't wrap it anymore. 

```{  { mixed with, blue theme, red theme, orange theme, yellow theme, green theme, purple theme, pink theme, neon theme, gold theme } and {blue background, red background, orange background, yellow background, green background, purple background, pink background| neon background, gold background}  |  }(: 1.2)```

# Inserting a prompt will reformat strength of dynamic prompts

```({ pink background| neon background | gold background} : 1.2), ```

this dynamic prompt is wrapped with 1,2 strength. but if i click to add a prompt from my collection into it the following occurs

```(: 1.2){ pink background| neon background | gold background} (: 1.2), myprompt```
as you can see it has the strength modifier added to the before and after the prompt for some reason. 

It would be great if dynamic prompts were better supported.

**Comment by AlpacaInTheNight** [comment]
New groups feature and bugfixes should resolve this issue. Your specific style should be working as expected now. Note the new style applying method - in some cases you may want to set it to "all", if you want to apply same prompts that are not part of a group.
